baseURL = "https://blog.nosugi.tech/"
disablePathToLower = false
languageCode = "en-us"
title = "nosugi blog"
theme = "robost1"
googleAnalytics = "UA-84084422-3"

[indexes]
category = "category"
tag = "tags"

[params]
paginate = true
twitter_username = "nosugi1"
[params.author]
name = "nosugi"
thumbnail = "images/avator.jpg"
facebook = ""
twitter = "https://twitter.com/nosugi1"
github = ""
description = "<center>行動や思考の軌跡を残します<br>経歴やポートフォリオは<a href='https://nosugi.tech'>ホームページ</a>で公開しています。</center>"