baseURL = "https://alltimeneet.com/"
disablePathToLower = false
languageCode = "en-us"
title = "All Time NEET"
theme = "robost1"
googleAnalytics = "UA-84084422-3"

[indexes]
category = "category"
tag = "tags"

[params]
paginate = true
twitter_username = "alltime_neet"

[params.author]
name = "Yusuke Sugino"
thumbnail = "images/avator.jpg"
facebook = ""
twitter = "https://twitter.com/alltime_neet"
github = ""
profile = "/profile"
description = "<center>行動や思考の軌跡を残します<br>なんとかして日本のニートの中でイケてるランキング上位10%ぐらいには入りたいなと思ってます</center>"