baseURL = "https://blog.nosugi.tech"
disablePathToLower = true
languageCode = "en-us"
title = "nosugi blog"
theme = "robost"
description = "nosugiのブログです。技術や思考の軌跡を記録として残しておきます。"

[indexes]
category = "category"
tag = "tags"

[params]
google_analytics_id = "UA-84084422-3"
paginate = true
twitter_username = "nosugi1"
[author]
name = "nosugi"
thumbnail = "thumb.jpg"
facebook = ""
twitter = "nogusi1"
github = ""