version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
        environment:
          TZ: Asia/Tokyo

    branches:
      ignore:
        - gh-pages
        - netlify-deploy

    steps:
      - checkout

      - run:
          name: "Setting for Git"
          command: |
            git config --global user.name "pipinosuke"
            git config --global user.email "ys.pipinosuke@gmail.com@gmail.com"

      # - run:
      #     name: "Up to date themes"
      #     command: |
      #       git submodule sync
      #       git submodule update --init --recursive

      - run:
          name: "Get GitHub repository"
          command: git clone git@github.com:pipinosuke/oldblog.git

      - run:
          name: "Build & Push"
          command: |
            git clone -b netlify-deploy git@github.com:pipinosuke/oldblog.git public
            rm -rf public/*
            hugo
            cd public
            git add .
            git commit -m "rebuilding site `date '+%Y-%m-%d'`"
            git push origin netlify-deploy